# -*- coding: utf-8 -*-
"""expt1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XRJvXFU7_v8oXlpni-hFLLGmPBlr4vXa
"""

a=int(input("Enter the number:"))
b=int(input("Enter the number:"))
c=a+b
print(c)